import {writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import type {Question,TopicId,Difficulty,Citation} from '../lib/types';

// Offline authoring only. The shipped site imports the resulting immutable JSON.
const bank:Question[]=[];
const tex=String.raw;
function add(family:string,topic:TopicId,difficulty:Difficulty,n:number,title:string,prompt:string,math:string,answer:number|string,answerTex:string,hints:string[],steps:string[],source:Citation,extra:Partial<Question>={}){
 const id=`${family}-${n}`;
 const fingerprint=createHash('sha256').update((prompt+' '+math).replace(/\s+/g,' ').trim()).digest('hex');
 bank.push({id,familyId:family,fingerprint,topic,difficulty,title,prompt,math,answer,answerTex,kind:typeof answer==='number'?'numeric':'choice',hints,steps,checklist:['I identified the relevant concept and its conditions.','My setup and intermediate steps agree with the solution.','I checked signs, bounds, and the final result.'],source,origin:'variation',eligible:true,verified:true,minutes:difficulty==='foundation'?3:difficulty==='standard'?5:8,...extra});
}
const src=(sheet:number,question:string,page=1):Citation=>({sheet,question,page});
for(const n of [2,3,4,5,6,7]){
 add('series-comparison','series','foundation',n,'Compare before calculating','Classify the series.',tex`\sum_{k=1}^{\infty}\frac{${n}+\cos k}{${n+1}^{k}}`,'Absolutely convergent',tex`\text{Absolutely convergent}`,[tex`Bound the numerator using $|\cos k|\leq1$.`,'Compare the absolute values to a geometric series.'],[tex`$|${n}+\cos k|\leq ${n+1}$.`,tex`$\sum ${n+1}/${n+1}^{k}$ is geometric with ratio $1/${n+1}<1$.`,'Absolute convergence follows by comparison.'],src(8,'1'),{options:['Absolutely convergent','Conditionally convergent','Divergent']});
 add('series-alternating','series','standard',n,'An alternating comparison','Classify the series.',tex`\sum_{k=1}^{\infty}\frac{(-1)^k}{\sqrt{k^2+${n}}}`,'Conditionally convergent',tex`\text{Conditionally convergent}`,['Check whether the positive magnitudes decrease to zero.','For absolute convergence, compare with the harmonic series.'],[tex`$b_k=1/\sqrt{k^2+${n}}$ decreases to zero, so the alternating series converges.`,tex`$\lim_{k\to\infty} k/\sqrt{k^2+${n}}=1$.`,'The absolute-value series diverges by limit comparison with the harmonic series.'],src(8,'2'),{options:['Absolutely convergent','Conditionally convergent','Divergent']});
 add('series-radius','series','standard',n,'Find the radius','Find the radius of convergence R. Enter a number.',tex`\sum_{k=1}^{\infty}\frac{(${n}x)^k}{k}`,1/n,tex`R=\frac1{${n}}`,['Apply the ratio test to the absolute values.','The factor k/(k+1) approaches one.'],[tex`$|a_{k+1}/a_k|=|${n}x|\,k/(k+1)\to |${n}x|$.`,tex`$|x|<1/${n}$ gives convergence, so $R=1/${n}$.`,'Endpoint tests affect the interval, not the radius.'],src(8,'8'));
 add('series-factorial','series','evaluative',n,'A factorial power series','Find the radius of convergence R. Enter a number.',tex`\sum_{k=1}^{\infty}\frac{(k!)^{${n}}}{(${n}k)!}x^k`,n**n,tex`R=${n}^{${n}}`,['Write the ratio of consecutive coefficients before simplifying.',tex`The denominator contains ${n} consecutive factors.`],[tex`$|a_{k+1}/a_k|=|x|\,(k+1)^{${n}}/\prod_{j=1}^{${n}}(${n}k+j)$.`,tex`The limit is $|x|/${n}^{${n}}$.`,tex`Convergence holds for $|x|<${n}^{${n}}$, so $R=${n**n}$.`],src(8,'8'));
 add('polar-circle','polar','foundation',n,'Read a polar circle','Find the radius of this circle.',tex`r=${2*n}\cos\theta`,n,`${n}`,[tex`Multiply by $r$ and substitute $r^2=x^2+y^2$.`,'Complete the square.'],[tex`$x^2+y^2=${2*n}x$.`,tex`$(x-${n})^2+y^2=${n*n}$.`,tex`The centre is $(${n},0)$ and radius is $${n}$.`],src(2,'11(a)'));
 add('polar-cartesian','polar','standard',n,'Convert the equation','The Cartesian equation is y = c x². Find c.',tex`r=${n}\tan\theta\sec\theta`,1/n,tex`c=\frac1{${n}}`,[tex`Use $\tan\theta=y/x$ and $\sec\theta=r/x$.`,'Cancel r away from the origin, then include the origin by continuity.'],[tex`$r=${n}yr/x^2$ gives $x^2=${n}y$.`,tex`Thus $y=x^2/${n}$; the original polar parameter includes the origin.`],src(2,'1(a)'));
 add('polar-region','polar','standard',n,'Understand the sector','Find the area of the region.',tex`0\leq r\leq ${n}\sec\theta,\qquad -\frac\pi4\leq\theta\leq\frac\pi4`,n*n,`${n*n}`,[tex`Convert $r\cos\theta\leq ${n}$ to an x bound.`,'The angle bounds are the lines y = ±x on the right half-plane.'],[tex`The region is $0\leq x\leq ${n},\ -x\leq y\leq x$.`,tex`Its area is $\int_0^{${n}}2x\,dx=${n*n}$.`],src(2,'3'));
 add('polar-overlap','double','evaluative',n,'Between a circle and a cardioid','Find the area inside the circle and outside the cardioid. This is polar integration practice.',tex`r=${3*n}\cos\theta,\qquad r=${n}(1+\cos\theta)`,n*n*(Math.PI/2),tex`\frac{${n*n}\pi}{2}`,[tex`Intersect: $3\cos\theta=1+\cos\theta$.`,'Use symmetry with the two intersection angles.'],[tex`$\cos\theta=1/2$, so the region runs from $-\pi/3$ to $\pi/3$.`,tex`$A=\frac{${n*n}}2\int_{-\pi/3}^{\pi/3}[9\cos^2\theta-(1+\cos\theta)^2]d\theta$.`,tex`The integrand is $8\cos^2\theta-2\cos\theta-1$; its integral is $2\pi$. The area is $${n*n}\pi$.`],src(2,'4'));
 const overlap=bank[bank.length-1];overlap.answer=n*n*Math.PI;overlap.answerTex=tex`${n*n}\pi`;
 add('polar-cardioid','polar','evaluative',n,'Locate a horizontal tangent','For the cardioid, find the positive nonzero polar angle in (0, π) where the tangent is horizontal. Enter the angle in radians.',tex`r=${n}(1+\cos\theta)`,Math.PI/3,tex`\theta=\pi/3`,[tex`Differentiate $y=r\sin\theta$ with respect to $\theta$.`,'Check that dx/dθ is nonzero at your candidate.'],[tex`$dy/d\theta=${n}(\cos\theta+\cos 2\theta)$.`,tex`$2\cos^2\theta+\cos\theta-1=0$ gives $\cos\theta=1/2$ or $-1$.`,tex`Only $\theta=\pi/3$ lies in $(0,\pi)$, and $dx/d\theta\ne0$.`],src(2,'11(a)'),{source:{sheet:2,question:'11(a)',page:1,label:'Polar graph skill extension from Sheet 2'}});
 add('vector-speed','vectors','foundation',n,'Speed along a helix','Find the constant speed.',tex`\mathbf r(t)=(${3*n}\cos t,${3*n}\sin t,${4*n}t)`,5*n,`${5*n}`,[tex`Differentiate each component of $\mathbf r$.`,'Speed is the magnitude of velocity.'],[tex`$\mathbf r'=(-${3*n}\sin t,${3*n}\cos t,${4*n})$.`,tex`$|\mathbf r'|=\sqrt{${9*n*n}(\sin^2t+\cos^2t)+${16*n*n}}=${5*n}$.`],src(1,'3'));
 add('vector-length','vectors','standard',n,'Arc length with a parameter','Calculate the arc length.',tex`\mathbf r(t)=(${n}\cos(2t),${n}\sin(2t),${n+1}t),\quad0\leq t\leq\pi`,Math.PI*Math.sqrt(4*n*n+(n+1)**2),tex`\pi\sqrt{${4*n*n+(n+1)**2}}`,['Differentiate carefully: the angular factor contributes a factor of two.','Integrate the speed over the stated parameter interval.'],[tex`$|\mathbf r'|=\sqrt{${4*n*n}+${(n+1)**2}}$.`,tex`$L=\int_0^\pi|\mathbf r'|dt=\pi\sqrt{${4*n*n+(n+1)**2}}$.`],src(1,'3'));
 add('vector-curvature','vectors','standard',n,'Curvature of a helix','Find the curvature.',tex`\mathbf r(t)=(${n}\cos t,${n}\sin t,${n+1}t)`,n/(n*n+(n+1)**2),tex`\frac{${n}}{${n*n+(n+1)**2}}`,['Compute the first and second derivatives.',tex`Use $\kappa=|\mathbf r'\times\mathbf r''|/|\mathbf r'|^3$.`],[tex`$|\mathbf r'|=\sqrt{${n*n+(n+1)**2}}$.`,tex`$|\mathbf r'\times\mathbf r''|=${n}\sqrt{${n*n+(n+1)**2}}$.`,tex`Division gives $\kappa=${n}/${n*n+(n+1)**2}$.`],src(1,'5'));
 add('vector-expcurvature','vectors','evaluative',n,'Curvature beyond a helix','Find the curvature at t = 0.',tex`\mathbf r(t)=(e^{${n}t}\cos t,e^{${n}t}\sin t,2)`,1/Math.sqrt(n*n+1),tex`\frac1{\sqrt{${n*n+1}}}`,[tex`At zero, $\mathbf r'=(${n},1,0)$.`,'Compute the second derivative before taking the cross product.'],[tex`$\mathbf r''(0)=(${n*n-1},${2*n},0)$.`,tex`$|\mathbf r'(0)\times\mathbf r''(0)|=${n*n+1}$ and $|\mathbf r'(0)|=\sqrt{${n*n+1}}$.`,tex`Therefore $\kappa(0)=1/\sqrt{${n*n+1}}$.`],src(1,'7'));
 add('limits-domain','limits','foundation',n,'The edge of the domain','The domain is an open disk. Find its radius.',tex`f(x,y)=\frac1{\sqrt{${n*n}-x^2-y^2}}`,n,`${n}`,['A square root in the denominator must be strictly positive.','Rewrite the resulting inequality as a disk.'],[tex`$${n*n}-x^2-y^2>0$.`,tex`The domain is $x^2+y^2<${n*n}$, an open disk of radius $${n}$.`],src(3,'1'));
 add('limits-bound','limits','standard',n,'Extend continuously','What value at the origin makes f continuous?',tex`f(x,y)=\frac{${n}x^2y^3}{2x^2+y^2}\quad ((x,y)\ne(0,0))`,0,'0',[tex`Use $x^2/(2x^2+y^2)\leq1/2$.`,'Bound the absolute value by something tending to zero.'],[tex`$|f(x,y)|\leq (${n}/2)|y|^3$.`,'The bound tends to zero as (x,y) approaches the origin, so the limit is zero.','Define f(0,0)=0. Testing a few paths alone would not prove this.'],src(3,'5'));
 add('limits-path','limits','standard',n,'Find the revealing path','For the given function, find the limit along y = x² as x → 0.',tex`f(x,y)=\frac{${n}x^2y}{x^4+y^2}`,n/2,tex`\frac{${n}}2`,['Substitute y = x² before taking the limit.','Cancel x⁴ only for x ≠ 0.'],[tex`$f(x,x^2)=${n}x^4/(2x^4)=${n}/2$.`,tex`The path limit is $${n}/2$. Along y=0 it is 0, so the full two-variable limit does not exist.`],src(3,'4'));
 add('limits-sine','limits','evaluative',n,'A limit needs a bound','Does the function extend continuously to the origin with value zero?',tex`f(x,y)=\frac{\sin^2(${n}x-y)}{|x|+|y|}`,'Yes',tex`\text{Yes, with limit }0`,[tex`Use $|\sin u|\leq|u|$.`,tex`Bound $|${n}x-y|$ by $${n}(|x|+|y|)$.`],[tex`$0\leq f(x,y)\leq ${n*n}(|x|+|y|)$.`,'The right side tends to zero from every direction.','The squeeze theorem proves continuity after setting f(0,0)=0.'],src(3,'3'),{options:['Yes','No']});
 add('partial-first','partials','foundation',n,'Keep the other variable fixed','Find fₓ(1,2).',tex`f(x,y)=${n}x^2y+\sin(x+y)`,4*n+Math.cos(3),tex`${4*n}+\cos3`,['Treat y as a constant when differentiating with respect to x.','Differentiate first, then substitute.'],[tex`$f_x=${2*n}xy+\cos(x+y)$.`,tex`$f_x(1,2)=${4*n}+\cos3$. Use radians.`],src(3,'6'));
 add('partial-mixed','partials','standard',n,'Two orders of differentiation','Find fₓᵧ(1,1).',tex`f(x,y)=x^{${n}}y^3`,3*n,`${3*n}`,['Differentiate first with respect to x, then with respect to y.','Evaluate after both derivatives.'],[tex`$f_x=${n}x^{${n-1}}y^3$.`,tex`$f_{xy}=${3*n}x^{${n-1}}y^2$, so $f_{xy}(1,1)=${3*n}$.`],src(3,'6'));
 add('partial-chain','partials','standard',n,'Follow the dependencies','Find du/dt at t = 1.',tex`u=x^2+${n}xy,\quad x=t^2,\quad y=t^3`,4+5*n,`${4+5*n}`,[tex`Use $du/dt=u_xx'+u_yy'$.`,'Alternatively substitute x and y into u first.'],[tex`$u(t)=t^4+${n}t^5$.`,tex`$u'(t)=4t^3+${5*n}t^4$, hence $u'(1)=${4+5*n}$.`],src(3,'8'));
 add('partial-mixed-origin','partials','evaluative',n,'Mixed partials at a point','Let fₓᵧ mean ∂/∂y(∂f/∂x). Find fₓᵧ(0,0).',tex`f(x,y)=\begin{cases}\dfrac{${n}(x^3y-xy^3)}{x^2+y^2}&(x,y)\ne(0,0),\\0&(x,y)=(0,0).\end{cases}`,-n,`${-n}`,['First find fₓ(0,y) directly from the difference quotient.','Then differentiate that one-variable function at y=0.'],[tex`For $y\ne0$, $f_x(0,y)=\lim_{h\to0}\frac{${n}(h^2y-y^3)}{h^2+y^2}=-${n}y$.`,tex`$f_x(0,0)=0$, so $f_{xy}(0,0)=-${n}$.`,tex`In contrast, $f_{yx}(0,0)=${n}$. The hypotheses guaranteeing equality do not hold here.`],src(3,'9',2));
 add('gradient-max','gradient','foundation',n,'The steepest possible change','Find the maximum directional derivative at (1,2,0).',tex`f(x,y,z)=${n}\sqrt{x^2+y^2+z^2}`,n,`${n}`,[tex`The maximum directional derivative is $|\nabla f|$.`,'The radial unit vector has magnitude one.'],[tex`$\nabla f=${n}(x,y,z)/\sqrt{x^2+y^2+z^2}$.`,tex`Its magnitude is $${n}$ at every nonzero point.`],src(4,'2'));
 add('gradient-direction','gradient','standard',n,'Normalize the direction','Find the directional derivative at P in the direction from P toward Q.',tex`f(x,y,z)=xy e^z,\quad P=(${n},${2*n},0),\quad Q=(0,0,0)`, -4*n/Math.sqrt(5),tex`-\frac{${4*n}}{\sqrt5}`,[tex`The direction is $Q-P$, not $P-Q$.`,'Normalize before taking the dot product.'],[tex`$\nabla f(P)=(${2*n},${n},${2*n*n})$.`,tex`$\mathbf u=(-1,-2,0)/\sqrt5$.`,tex`$D_{\mathbf u}f=-${4*n}/\sqrt5$.`],src(4,'1'));
 add('gradient-plane','gradient','standard',n,'A plane near a surface','The tangent plane at P is z = Ax + By + C. Find C.',tex`z=x^2-y^2,\quad P=(${n},1,${n*n-1})`,-n*n+1,`${1-n*n}`,['The slopes are fₓ=2x and fᵧ=−2y.','Expand the point-slope form of the tangent plane.'],[tex`$z-(${n*n-1})=${2*n}(x-${n})-2(y-1)$.`,tex`$z=${2*n}x-2y+(${1-n*n})$.`],src(4,'4'));
 add('gradient-intersection','gradient','evaluative',n,'A tangent to an intersection','A tangent direction is ∇F × ∇G at P. Find its y-component, using exactly that order.',tex`F=x^2+y^2-z,\quad G=z+y-${n*n},\quad P=(${n},-1,${n*n+1})`,-2*n,`${-2*n}`,['Both surface normals are perpendicular to the intersection tangent.','Compute the ordered cross product; its sign matters here.'],[tex`$\nabla F(P)=(${2*n},-2,-1)$ and $\nabla G=(0,1,1)$.`,tex`$\nabla F\times\nabla G=(-1,-${2*n},${2*n})$.`,tex`The y-component is $-${2*n}$.`],src(4,'3'));
 add('optimization-classify','optimization','foundation',n,'Classify the critical point','Classify the critical point at the origin.',tex`f(x,y)=${n}x^2-${n+1}y^2`,'Saddle point',tex`\text{Saddle point}`,['Compare the signs along the x and y axes.','Or calculate the Hessian determinant.'],[tex`$f(x,0)=${n}x^2>0$ for nonzero x, while $f(0,y)=-${n+1}y^2<0$.`,tex`Also, $D=f_{xx}f_{yy}-f_{xy}^2=-${4*n*(n+1)}<0$.`,'The origin is a saddle point.'],src(4,'6'),{options:['Local minimum','Local maximum','Saddle point']});
 add('optimization-box','optimization','standard',n,'An open-top box','An open-top rectangular box has the given volume. Find the side length of the square base that minimizes surface area.',tex`V=${4*n**3}`,2*n,`${2*n}`,['Write surface area as xy + 2V/x + 2V/y.','The stationary conditions force x=y.'],[tex`$S=xy+2V/x+2V/y$. The equations $y=2V/x^2$, $x=2V/y^2$ imply $x=y$.`,tex`$x^3=2V=${8*n**3}$, so $x=${2*n}$ and height $h=${n}$.`,'The area grows without bound at the boundary of the positive domain, so this unique stationary point is the global minimum.'],src(4,'5'));
 add('optimization-sphere','optimization','standard',n,'Symmetry with a constraint','Find the maximum of a²b²c² on the sphere.',tex`a^2+b^2+c^2=${3*n}`,n**3,`${n**3}`,[tex`Apply AM–GM to $a^2,b^2,c^2$.`,'Equality requires all three squares to be equal.'],[tex`$(a^2b^2c^2)^{1/3}\leq(a^2+b^2+c^2)/3=${n}$.`,tex`Therefore the maximum is $${n**3}$, attained when $a^2=b^2=c^2=${n}$.`],src(4,'10(a)'));
 add('optimization-hyperbola','optimization','evaluative',n,'Nearest point on a quadratic','Find the square of the shortest distance from the origin to this curve in the plane z=0.',tex`x^2+8xy+7y^2=${15*n}`,15*n/9,tex`\frac{${5*n}}3`,['Use the symmetric quadratic-form matrix [[1,4],[4,7]].','Its eigenvalues are 9 and −1.'],[tex`The quadratic form is at most $9(x^2+y^2)$.`,tex`The constraint implies $x^2+y^2\geq ${15*n}/9=${5*n}/3$.`,tex`Equality is attained along the eigenvector $(1,2)$, after scaling to satisfy the constraint.`],src(4,'8'));
 add('double-rectangle','double','foundation',n,'Start with an iterated integral','Evaluate the integral.',tex`\int_0^1\int_0^{${n}}xy\,dy\,dx`,n*n/4,tex`\frac{${n*n}}4`,['Integrate with respect to y first; x is constant.','Then integrate the resulting linear function of x.'],[tex`$\int_0^{${n}}xy\,dy=${n*n}x/2$.`,tex`$\int_0^1${n*n}x/2\,dx=${n*n}/4$.`],src(5,'1'));
 add('double-volume','double','standard',n,'Volume under a cylinder','Find the volume between z=y² and the xy-plane over the rectangle.',tex`0\leq x\leq ${n},\quad -${n-1}\leq y\leq ${n-1}`,2*n*(n-1)**3/3,tex`\frac{${2*n*(n-1)**3}}3`,['Integrate the height y² over the base.','The y-integral is even.'],[tex`$V=\int_0^{${n}}\int_{-${n-1}}^{${n-1}}y^2\,dy\,dx$.`,tex`$V=${n}\cdot 2(${n-1})^3/3=${2*n*(n-1)**3}/3$.`],src(5,'6'));
 add('double-reverse','double','standard',n,'Change the order','Evaluate the integral by reversing the order.',tex`\int_0^{${n}}\int_x^{${n}}2y\cos(y^2)\,dy\,dx`,0,'',[],[],src(5,'3'),{verified:false});
 // Use a reverse-order integral whose antiderivative is elementary.
 const rev=bank.pop()!;
 add('double-reverse','double','standard',n,'Change the order','Evaluate the integral by reversing the order.',tex`\int_0^{${n}}\int_y^{${n}}\cos(x^2)\,dx\,dy`,Math.sin(n*n)/2,tex`\frac{\sin(${n*n})}{2}`,['Sketch 0 ≤ y ≤ x ≤ n.','Integrating first with respect to y introduces the factor x.'],[tex`$I=\int_0^{${n}}\int_0^x\cos(x^2)\,dy\,dx=\int_0^{${n}}x\cos(x^2)\,dx$.`,tex`With $u=x^2$, $I=\sin(${n*n})/2$. Use radians.`],rev.source);
 add('triple-volume','triple','foundation',n,'Volume of a simplex','Find the volume in the first octant.',tex`x+y+z\leq ${n}`,n**3/6,tex`\frac{${n**3}}6`,['The solid is a tetrahedron with three equal intercepts.','Set up z from 0 to n−x−y.'],[tex`$V=\int_0^{${n}}\int_0^{${n}-x}\int_0^{${n}-x-y}dz\,dy\,dx$.`,tex`$V=\frac12\int_0^{${n}}(${n}-x)^2dx=${n**3}/6$.`],src(5,'5'));
 add('triple-average','triple','standard',n,'Average over a solid','Find the average value of F over the box.',tex`F=x+y-z,\quad 0\leq x\leq ${n},\quad0\leq y\leq ${n+1},\quad0\leq z\leq ${n+2}`,(n-1)/2,tex`\frac{${n-1}}2`,['The average of a linear function over a rectangular solid equals its value at the centre.','Or integrate F and divide by volume.'],[tex`$\bar x=${n}/2$, $\bar y=${n+1}/2$, $\bar z=${n+2}/2$.`,tex`$\overline F=(${n}+${n+1}-${n+2})/2=${n-1}/2$.`],src(5,'7'));
 add('triple-jacobian','triple','standard',n,'Keep the Jacobian','Find the absolute value of ∂(x,y,z)/∂(u,v,w) at u=2.',tex`u=x,\quad v=xy,\quad w=${n}z`,1/(2*n),tex`\frac1{${2*n}}`,['Invert the transformation: x=u, y=v/u, z=w/n.','The inverse Jacobian is triangular.'],[tex`$\partial(x,y,z)/\partial(u,v,w)=1/(${n}u)$.`,tex`At $u=2$, the absolute value is $1/${2*n}$.`],src(5,'10'));
 add('triple-cone','triple','evaluative',n,'A sphere above a cone','Find the volume of the solid inside the sphere and above the cone.',tex`x^2+y^2+z^2\leq ${n*n},\qquad z\geq\sqrt{x^2+y^2}`,2*Math.PI*n**3/3*(1-1/Math.sqrt(2)),tex`\frac{${2*n**3}\pi}{3}\left(1-\frac1{\sqrt2}\right)`,['In spherical coordinates, the cone is φ=π/4.','Use 0 ≤ ρ ≤ n and include ρ²sinφ.'],[tex`$V=\int_0^{2\pi}\int_0^{\pi/4}\int_0^{${n}}\rho^2\sin\phi\,d\rho\,d\phi\,d\theta$.`,tex`$V=2\pi\cdot(${n**3}/3)\cdot(1-1/\sqrt2)$.`],src(5,'11'));
 add('line-potential','line','foundation',n,'Use a potential function','Find the work done along any smooth path from A to B.',tex`\mathbf F=\nabla(xyz),\quad A=(1,1,1),\quad B=(${n},2,3)`,6*n-1,`${6*n-1}`,['A gradient field has path-independent work.','Evaluate the potential at the endpoints.'],[tex`$W=f(B)-f(A)=(${n})(2)(3)-1=${6*n-1}$.`,'The potential is smooth throughout space, so the fundamental theorem applies.'],src(6,'9',2));
 add('line-flux','line','standard',n,'Outward flux in the plane','Find the outward flux across the circle.',tex`\mathbf F=(${n}x,-${n+1}y),\quad x^2+y^2=${n*n}`,-Math.PI*n*n,tex`-${n*n}\pi`,['Use the flux form of Green’s theorem.','Compute Pₓ+Qᵧ, not Qₓ−Pᵧ.'],[tex`$\nabla\cdot\mathbf F=${n}-(${n+1})=-1$.`,tex`Outward flux $=\iint_D(-1)dA=-${n*n}\pi$.`],src(6,'5'));
 add('line-green','line','standard',n,'Circulation via Green','Find the counterclockwise circulation around C.',tex`\oint_C(${n}y+x)\,dx+(y+${n+2}x)\,dy,\quad C:(x-2)^2+(y-3)^2=${n*n}`,2*Math.PI*n*n,tex`${2*n*n}\pi`,['Use Qₓ−Pᵧ for positive circulation.','Translation of the circle does not change its area.'],[tex`$Q_x-P_y=${n+2}-${n}=2$.`,tex`The disk area is $${n*n}\pi$, hence circulation is $${2*n*n}\pi$.`],src(6,'11',2));
 add('line-quartic','line','evaluative',n,'Green’s theorem with symmetry','Find the counterclockwise circulation.',tex`\mathbf F=(-x^2y,xy^2),\quad C:x^2+y^2=${n*n}`,Math.PI*n**4/2,tex`\frac{${n**4}\pi}{2}`,[tex`$Q_x-P_y=y^2+x^2$.`,'Integrate r² over the disk, including the polar area factor.'],[tex`$\oint_C\mathbf F\cdot d\mathbf r=\iint_D(x^2+y^2)dA$.`,tex`$=\int_0^{2\pi}\int_0^{${n}}r^3dr\,d\theta=${n**4}\pi/2$.`],src(6,'10',2));
 add('surface-plane','surface','foundation',n,'Surface area of a plane','Find the area of this portion of the plane.',tex`z=${n}x+2y,\qquad0\leq x\leq1,\quad0\leq y\leq2`,2*Math.sqrt(n*n+5),tex`2\sqrt{${n*n+5}}`,[tex`For $z=g(x,y)$, $dS=\sqrt{1+g_x^2+g_y^2}\,dx\,dy$.`,'The factor is constant over this rectangle.'],[tex`$dS=\sqrt{1+${n*n}+4}\,dx\,dy$.`,tex`The base area is 2, so $S=2\sqrt{${n*n+5}}$.`],src(7,'1'));
 add('surface-hemisphere','surface','standard',n,'Integrate over a hemisphere','Evaluate the scalar surface integral over the upper hemisphere.',tex`\iint_S z^2\,dS,\quad x^2+y^2+z^2=${n*n},\quad z\geq0`,2*Math.PI*n**4/3,tex`\frac{${2*n**4}\pi}{3}`,[tex`Use $z=${n}\cos\phi$ and $dS=${n*n}\sin\phi\,d\phi d\theta$.`,'The upper hemisphere has 0 ≤ φ ≤ π/2.'],[tex`$I=${n**4}\int_0^{2\pi}\int_0^{\pi/2}\cos^2\phi\sin\phi\,d\phi\,d\theta$.`,tex`The angular integral is $1/3$, so $I=${2*n**4}\pi/3$.`],src(7,'9'));
 add('surface-stokes','surface','standard',n,'Choose the easier spanning surface','Find the circulation, counterclockwise when viewed from above.',tex`\mathbf F=(-y,x,z),\quad C:x^2+y^2=${n*n},\quad z=2`,2*Math.PI*n*n,tex`${2*n*n}\pi`,['Use the flat disk bounded by C.','Its upward normal agrees with the stated orientation.'],[tex`$\nabla\times\mathbf F=(0,0,2)$.`,tex`Stokes gives $\oint_C\mathbf F\cdot d\mathbf r=2\operatorname{area}(D)=${2*n*n}\pi$.`],src(7,'7'));
 add('surface-cap','surface','evaluative',n,'Close an open surface','Find the outward flux, away from the z-axis, through the curved paraboloid only.',tex`\mathbf F=(x,y,z),\quad S:z=x^2+y^2,\quad0\leq z\leq ${n*n}`,Math.PI*n**4/2,tex`\frac{${n**4}\pi}{2}`,[tex`The outward vector area is $(2x,2y,-1)dxdy$.`,'On the surface, F dotted with this vector equals x²+y².'],[tex`$\mathbf F\cdot(2x,2y,-1)=2x^2+2y^2-z=x^2+y^2$.`,tex`$\Phi=\int_0^{2\pi}\int_0^{${n}}r^3dr\,d\theta=${n**4}\pi/2$.`,'Equivalently close the top disk and subtract its flux from the divergence-theorem result.'],src(7,'10'));
}

// Original tutorial questions/subparts, transcribed with independently derived solutions.
add('t1-q1','vectors','standard',0,'Velocity meets acceleration','Find the angle between velocity and acceleration at t=0. Enter radians.',tex`\mathbf r(t)=(3\sin t,\sin3t,3t^2)`,Math.PI/2,tex`\pi/2`,['Differentiate twice, then evaluate at t=0.'],[tex`$\mathbf v(0)=(3,3,0)$ and $\mathbf a(0)=(0,0,6)$.`,'Their dot product is zero and both are nonzero, so the angle is π/2.'],src(1,'1 (angle subpart)'),{origin:'tutorial'});
add('t1-q3','vectors','standard',0,'Arc length of the supplied helix','Find the arc length.',tex`\mathbf r(t)=(\cos3t,\sin3t,3t),\quad0\leq t\leq 2\pi/3`,2*Math.PI*Math.sqrt(2),tex`2\sqrt2\pi`,['Differentiate all three components.'],[tex`$|\mathbf r'|=\sqrt{9\sin^2(3t)+9\cos^2(3t)+9}=3\sqrt2$.`,tex`$L=3\sqrt2\cdot2\pi/3=2\sqrt2\pi$.`],src(1,'3(i)'),{origin:'tutorial'});
add('t2-q3','polar','standard',0,'Sketch a polar region','Sketch the region and find its area.',tex`0\leq r\leq2\sec\theta,\quad-\pi/4\leq\theta\leq\pi/4`,4,'4',['Use x=r cosθ and identify the two angle boundaries.'],[tex`$0\leq x\leq2$ and $-x\leq y\leq x$.`,'This is a triangle with vertices (0,0), (2,2), (2,−2); its area is 4.'],src(2,'3'),{origin:'tutorial'});
add('t2-q11','polar','foundation',0,'A circle in polar form','Find the radius of this circle.',tex`r=4\cos\theta`,2,'2',['Multiply by r and complete the square.'],[tex`$x^2+y^2=4x$, so $(x-2)^2+y^2=4$.`,'The centre is (2,0) and the radius is 2.'],src(2,'11(a)'),{origin:'tutorial'});
add('t3-q1','limits','foundation',0,'An open or closed domain?','Classify the domain of this function.',tex`f(x,y)=\frac1{\sqrt{25-x^2-y^2}}`,'Open and bounded',tex`x^2+y^2<25`,['The radicand must be strictly positive.'],[tex`The domain is $x^2+y^2<25$.`,'It excludes its boundary circle and lies inside a disk of finite radius.'],src(3,'1 (domain subpart)'),{origin:'tutorial',options:['Open and bounded','Closed and bounded','Open and unbounded','Neither open nor closed']});
add('t3-q4','limits','standard',0,'Discontinuity at the origin','Prove that the function is discontinuous at the origin.',tex`f(x,y)=\begin{cases}\dfrac{x^2y}{x^4+y^2}&(x,y)\ne(0,0),\\0&(x,y)=(0,0).\end{cases}`,'self',tex`\text{Discontinuous}`,['Compare y=0 with y=x².'],[tex`For $x\ne0$, $f(x,0)=0$.`,tex`For $x\ne0$, $f(x,x^2)=1/2$.`,'The different path limits prove the full limit does not exist, hence f is discontinuous.'],src(3,'4'),{kind:'self',origin:'tutorial',checklist:['I used two paths approaching the origin.','I obtained limits 0 and 1/2.','I concluded that the full limit fails to exist.']});
add('t4-q1','gradient','standard',0,'A direction toward the origin','Find the directional derivative at P toward Q.',tex`g=xy e^z,\quad P=(2,4,0),\quad Q=(0,0,0)`,-8/Math.sqrt(5),tex`-8/\sqrt5`,['Normalize Q−P before taking the dot product.'],[tex`$\nabla g(P)=(4,2,8)$ and $\mathbf u=(-1,-2,0)/\sqrt5$.`,tex`$D_{\mathbf u}g=-8/\sqrt5$.`],src(4,'1'),{origin:'tutorial'});
add('t4-q2','gradient','foundation',0,'Maximum directional derivative','Find the maximum directional derivative at (1,4,2).',tex`f(x,y,z)=\sqrt{x^2+y^2+z^2}`,1,'1',['Take the magnitude of the gradient.'],[tex`$\nabla f=(x,y,z)/\sqrt{x^2+y^2+z^2}$.`,'Its magnitude at every nonzero point is 1.'],src(4,'2 (maximum subpart)'),{origin:'tutorial'});
add('t4-q5','optimization','standard',0,'Minimize the material','An open-top rectangular box must have volume 32 cubic feet. Find the side of the optimal square base.',tex`V=32`,4,'4',['Express height as 32/(xy) and minimize area.'],[tex`$S=xy+64/x+64/y$. Stationarity gives $x=y$ and $x^3=64$.`,'The base is 4 ft by 4 ft and height is 2 ft. Area diverges on the positive-domain boundary, so this is the global minimum.'],src(4,'5'),{origin:'tutorial'});
add('t4-q8','optimization','evaluative',0,'Shortest distance to the hyperbola','Find the shortest distance from the origin to the curve.',tex`x^2+8xy+7y^2=255,\quad z=0`,Math.sqrt(85/3),tex`\sqrt{85/3}`,['The quadratic-form matrix has largest eigenvalue 9.'],[tex`$x^2+8xy+7y^2\leq9(x^2+y^2)$.`,tex`$x^2+y^2\geq255/9=85/3$, attained along $(1,2)$.`,tex`The distance is $\sqrt{85/3}$.`],src(4,'8'),{origin:'tutorial'});
add('t5-q6','double','standard',0,'Volume under the parabolic cylinder','Find the volume between the cylinder and the xy-plane over the stated rectangle.',tex`z=y^2,\quad0\leq x\leq1,\quad-1\leq y\leq1`,2/3,tex`2/3`,['Integrate the nonnegative height over the base.'],[tex`$V=\int_0^1\int_{-1}^1y^2\,dy\,dx=2/3$.`],src(5,'6'),{origin:'tutorial'});
add('t5-q7','triple','standard',0,'Average value in a box','Find the average value of F over the solid.',tex`F=x+y-z,\quad0\leq x\leq1,\quad0\leq y\leq1,\quad0\leq z\leq2`,0,'0',['Divide the volume integral by the volume, or use the centre for a linear function.'],[tex`$\overline F=1/2+1/2-1=0$.`,'The average equals the value at the centre because F is linear.'],src(5,'7'),{origin:'tutorial'});
add('t6-q4','line','foundation',0,'A closed path in a gradient field','Find the work done counterclockwise around the circle from (2,0) back to itself.',tex`\mathbf F=\nabla(x+y)^2,\quad x^2+y^2=4`,0,'0',['Use the potential at the endpoints.'],['The potential (x+y)² is smooth on the plane.','The endpoints coincide, so work equals the potential difference, which is zero.'],src(6,'4'),{origin:'tutorial'});
add('t6-q9','line','standard',0,'Recognize an exact differential','Evaluate the line integral.',tex`\int_{(1,1,2)}^{(3,5,0)}yz\,dx+xz\,dy+xy\,dz`,-2,'-2',['Recognize d(xyz).'],[tex`$d(xyz)=yz\,dx+xz\,dy+xy\,dz$.`,tex`$W=(3)(5)(0)-(1)(1)(2)=-2$.`],src(6,'9',2),{origin:'tutorial'});
add('t6-q11','line','standard',0,'Green’s theorem on a shifted circle','Evaluate for counterclockwise orientation.',tex`\oint_C(6y+x)\,dx+(y+2x)\,dy,\quad C:(x-2)^2+(y-3)^2=4`,-16*Math.PI,tex`-16\pi`,['Subtract Pᵧ from Qₓ.'],[tex`$Q_x-P_y=2-6=-4$.`,tex`The disk has area $4\pi$, so circulation is $-16\pi$.`],src(6,'11',2),{origin:'tutorial'});
add('t8-q2','series','standard',0,'Absolute or conditional?','Classify the series.',tex`\sum_{n=1}^{\infty}\frac{(-1)^n}{\sqrt{n^2+1}}`,'Conditionally convergent',tex`\text{Conditionally convergent}`,['Use the alternating-series test, then a limit comparison.'],['The magnitudes decrease to zero, so the alternating series converges.','The absolute-value terms have ratio tending to 1 relative to 1/n, so absolute convergence fails.'],src(8,'2'),{origin:'tutorial',options:['Absolutely convergent','Conditionally convergent','Divergent']});

// Scored mock questions: source evaluatives, exact prompts or explicitly named subparts.
const ev=(question:string,page=1):Citation=>({path:'Evaluatives/Quizzes/2021-22/(2021-22)Quiz_2.pdf',question,page,label:'2021–22 Quiz 2 · Set A'});
add('exam-21-q1','double','evaluative',0,'Reverse the order','Which integral has the same region and integrand?',tex`I=\int_0^1\int_0^{x^2}xy^2\,dy\,dx`,'D',tex`\int_0^1\int_{\sqrt y}^1xy^2\,dx\,dy`,['Sketch y=x² for x between 0 and 1.'],[tex`The region $0\leq y\leq x^2$, $0\leq x\leq1$ becomes $0\leq y\leq1$, $\sqrt y\leq x\leq1$.`],ev('1'),{origin:'evaluative',options:[tex`A: $\int_0^1\int_0^{y^2}xy^2\,dx\,dy$`,tex`B: $\int_0^1\int_0^{\sqrt y}xy^2\,dx\,dy$`,tex`C: $\int_0^1\int_{\sqrt y}^{1/2}xy^2\,dx\,dy$`,tex`D: $\int_0^1\int_{\sqrt y}^{1}xy^2\,dx\,dy$`]});
add('exam-21-q2','double','standard',0,'A separable double integral','Evaluate I.',tex`I=\int_0^1\int_0^1\frac{1+x^2}{1+y^2}\,dy\,dx`,Math.PI/3,tex`\pi/3`,['The rectangle and separable integrand allow a product of two integrals.'],[tex`$I=(\int_0^1(1+x^2)dx)(\int_0^1(1+y^2)^{-1}dy)=(4/3)(\pi/4)=\pi/3$.`],ev('2'),{origin:'evaluative'});
add('exam-21-q3','double','evaluative',0,'An area between curves','Find the area bounded by the curves.',tex`y=2\sqrt x,\quad y=-x,\quad x=1,\quad x=4`,101/6,tex`101/6`,['Integrate upper curve minus lower curve.'],[tex`$A=\int_1^4(2\sqrt x+x)dx=[\frac43x^{3/2}+\frac12x^2]_1^4=101/6$.`],ev('3'),{origin:'evaluative'});
add('exam-21-q7','triple','evaluative',0,'A cylindrical integral','Evaluate the integral.',tex`\int_0^1\int_0^{\sqrt z}\int_0^{2\pi}(r^2\cos^2\theta+z^2)r\,d\theta\,dr\,dz`,Math.PI/3,tex`\pi/3`,[tex`Integrate $\cos^2\theta$ over a full turn.`],[tex`The angular integral is $\pi r^3+2\pi z^2r$.`,tex`After r-integration: $\pi z^2/4+\pi z^3$.`,tex`The final integral is $\pi/12+\pi/4=\pi/3$.`],ev('7',2),{origin:'evaluative'});
add('exam-21-q9','triple','standard',0,'Bounds of a solid','V has the displayed form. Find f(1,1) − g(0).',tex`V=\int_0^2\int_0^{g(x)}\int_0^{f(x,y)}dz\,dy\,dx,\qquad z=4-x^2-y`,-2,'-2',['At z=0, the top y boundary is 4−x².'],[tex`$f(x,y)=4-x^2-y$ and $g(x)=4-x^2$.`,tex`$f(1,1)-g(0)=2-4=-2$.`],ev('9',2),{origin:'evaluative'});
add('exam-21-q12','line','evaluative',0,'Circulation with density','Find the circulation of F around C in the stated direction.',tex`\mathbf F=0.2(x-y,x^2),\quad C:\mathbf r(t)=(\sin t,-\cos t),\quad0\leq t\leq2\pi`,Math.PI/5,tex`\pi/5`,['The curve is counterclockwise; apply Green’s theorem.'],[tex`$Q_x-P_y=0.2(2x+1)$.`,'The integral of x over the unit disk is zero by symmetry.',tex`Circulation is $0.2\pi=\pi/5$.`],ev('12',3),{origin:'evaluative'});
add('exam-21-q14','line','evaluative',0,'Conditions for gradient fields','Which pair (a,b) makes both fields gradient fields?',tex`\mathbf F=(y^2+2x,axy),\quad\mathbf G=e^{x+y}(x+b,x)`,'C',tex`a=2,\ b=1`,['In the plane, compare the two cross partial derivatives.'],[tex`For F: $2y=ay$, giving $a=2$.`,tex`For G: $e^{x+y}(x+b)=e^{x+y}(x+1)$, giving $b=1$.`,'Both fields are smooth on the simply connected plane, so the condition is sufficient.'],ev('14',3),{origin:'evaluative',options:['A: a=1, b=2','B: a=1, b=1','C: a=2, b=1','D: a=2, b=2']});
const ev22=(question:string,page=1):Citation=>({path:'Evaluatives/Quizzes/2022-23/(2022-23)Quiz2_announced.pdf',question,page,label:'2022–23 Quiz 2 · Set A'});
add('exam-22-q1','line','standard',0,'Choose a potential','Which function is a potential for F?',tex`\mathbf F=(y+z,x+z,x+y)`,'B',tex`f=xy+yz+zx+1`,['Differentiate each proposed potential.'],[tex`$\nabla(xy+yz+zx+1)=(y+z,x+z,x+y)$.`],ev22('1'),{origin:'evaluative',options:[tex`A: $xy+yz-zx+10$`,tex`B: $xy+yz+zx+1$`,tex`C: $xy-yz+zx+10$`,tex`D: $xy-yz-zx+1$`]});
add('exam-22-q3','line','standard',0,'Outward flux across a square','Find the outward flux.',tex`\mathbf F=(x-2y,y-2x),\quad0\leq x\leq1,\quad0\leq y\leq1`,2,'2',['Integrate the divergence over the square.'],[tex`$\nabla\cdot\mathbf F=1+1=2$.`,'The square has area 1, so the outward flux is 2.'],ev22('3'),{origin:'evaluative'});
add('exam-22-q4','line','foundation',0,'Work along a piecewise path','Find the work along (0,0,0) → (0,0,1) → (0,1,1) → (1,1,1).',tex`\mathbf F=\nabla(xyz)`,1,'1',['A gradient field reduces work to a potential difference.'],[tex`$W=xyz|_{(1,1,1)}-xyz|_{(0,0,0)}=1-0=1$.`],ev22('4',2),{origin:'evaluative'});

// Prefer the original if the same question occurs as a generated instance.
const unique=new Map<string,Question>();
for(const q of bank){
 q.fingerprint=createHash('sha256').update(q.math.replace(/\s+/g,'')+'|'+q.kind+'|'+String(q.answer)).digest('hex');
 const old=unique.get(q.fingerprint);if(!old||q.origin==='tutorial')unique.set(q.fingerprint,q);
}
const questions=[...unique.values()];
for(const q of questions){if(!q.verified||!q.hints.length||!q.steps.length||typeof q.answer==='number'&&!Number.isFinite(q.answer))throw Error('Invalid item '+q.id);}
mkdirSync('content',{recursive:true});
writeFileSync('content/questions.json',JSON.stringify(questions,null,2));
writeFileSync('content/bank-audit.json',JSON.stringify({version:1,questionCount:questions.length,families:new Set(questions.map(q=>q.familyId)).size,originalTutorial:questions.filter(q=>q.origin==='tutorial').length,evaluatives:questions.filter(q=>q.origin==='evaluative').length,variations:questions.filter(q=>q.origin==='variation').length,complete:false,notes:['Only the explicitly curated items are scored. Remaining tutorial questions require transcription and verification.','2022–23 Quiz 2 Set A Q2 is excluded: its supplied key contradicts the connectedness of the displayed convex sets.','Historical polar arc length, projectile motion, and error estimation are excluded from recommended practice.']},null,2));
console.log(`Wrote ${questions.length} checked questions across ${new Set(questions.map(q=>q.topic)).size} topics.`);
