/* SVG graphs need an image role for their accessible description. */
/* oxlint-disable jsx-a11y/prefer-tag-over-role */
'use client';

import {useState} from 'react';

import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';

import {Slider} from '@/components/ui/slider';

import {MathText} from './math';

function Control({label,value,min,max,step=1,onChange}:{label:string;value:number;min:number;max:number;step?:number;onChange:(n:number)=>void}){return <div className="control"><div className="control-label">{label}<output>{Number(value.toFixed(2))}</output></div><Slider aria-label={label} value={[value]} min={min} max={max} step={step} onValueChange={v=>onChange(Array.isArray(v)?v[0]:v)}/></div>}

function Grid({axes=true}:{axes?:boolean}){return <g stroke="#dce7ed" strokeWidth="1">{Array.from({length:13},(_,i)=><g key={i}><line x1={i*40} y1="0" x2={i*40} y2="480"/><line x1="0" y1={i*40} x2="480" y2={i*40}/></g>)}{axes&&<path d="M0 240H480M240 0V480" stroke="#819aa9" strokeWidth="1.5"/>}</g>}

export default function Explorers(){

 const [a,setA]=useState(2),[b,setB]=useState(2),[angle,setAngle]=useState(35),[x,setX]=useState(1),[y,setY]=useState(1),[slice,setSlice]=useState(.55),[reverse,setReverse]=useState(false);

 const scale=200/Math.max(4,a+b);const polar=Array.from({length:361},(_,i)=>{const t=i*Math.PI/180,r=a+b*Math.cos(t);return `${240+scale*r*Math.cos(t)},${240-scale*r*Math.sin(t)}`}).join(' ');

 const theta=angle*Math.PI/180,derivative=2*x*Math.cos(theta)+2*y*Math.sin(theta);

 const areaPath='M80 390 L400 390 '+Array.from({length:101},(_,i)=>{const t=1-i/100;return `L${80+320*t} ${390-300*t*t}`}).join(' ')+' Z';

 return <><h1>See what the symbols mean.</h1><p className="intro">Move a control. Make a prediction. Check what changes.</p><Tabs defaultValue="polar"><TabsList><TabsTrigger value="polar">Polar curves</TabsTrigger><TabsTrigger value="gradient">Gradients</TabsTrigger><TabsTrigger value="region">Integration regions</TabsTrigger></TabsList>

 <TabsContent value="polar"><div className="lab-grid"><div className="plot"><svg viewBox="0 0 480 480" role="img" aria-label={`Polar graph of r equals ${a} plus ${b} cosine theta`}><Grid/><polyline points={polar} fill="#53b6a817" stroke="#138b83" strokeWidth="3"/><circle cx="240" cy="240" r="4" fill="#16394b"/><text x="453" y="258" fill="#6b8699" fontSize="13">x</text><text x="250" y="20" fill="#6b8699" fontSize="13">y</text></svg><div className="plot-caption">One grid square = {Number((40/scale).toFixed(2))} units. A full turn traces the curve.</div></div><section className="panel"><h2>From circle to limaçon</h2><div className="formula"><MathText tex={`r=${a}+${b}\\cos\\theta`}/></div><Control label="Constant term a" value={a} min={0} max={4} step={.1} onChange={setA}/><Control label="Cosine coefficient b" value={b} min={0} max={4} step={.1} onChange={setB}/><div className="notice info">{b===0?'With b=0, the radius is constant: a circle.':a===b?'When a=b, the curve is a cardioid with a cusp at the origin.':a<b?'When a<b, negative radii create an inner loop.':'With a>b, the curve has no inner loop.'}</div><p>Predict the effect of increasing a while keeping b fixed. Then check the intercept at θ = 0.</p><div className="formula"><MathText tex={`r(0)=${Number((a+b).toFixed(2))}`}/></div></section></div></TabsContent>

 <TabsContent value="gradient"><div className="lab-grid"><div className="plot"><svg viewBox="0 0 480 480" role="img" aria-label={`Level curves of x squared plus y squared, gradient at (${x},${y}), and selected direction`}><defs><marker id="arrow-teal" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0L6 3L0 6Z" fill="#078d80"/></marker><marker id="arrow-blue" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0L6 3L0 6Z" fill="#446ead"/></marker></defs><Grid/>{[1,2,3,4,5].map(r=><circle key={r} cx="240" cy="240" r={r*40} fill="none" stroke="#8ecbc4" strokeWidth="1.5"/>)}<line x1={240+40*x} y1={240-40*y} x2={240+40*x+35*2*x} y2={240-40*y-35*2*y} stroke="#078d80" strokeWidth="3" markerEnd="url(#arrow-teal)"/><line x1={240+40*x} y1={240-40*y} x2={240+40*x+80*Math.cos(theta)} y2={240-40*y-80*Math.sin(theta)} stroke="#446ead" strokeWidth="3" markerEnd="url(#arrow-blue)"/><circle cx={240+40*x} cy={240-40*y} r="6" fill="#14374b"/></svg><div className="plot-caption">Teal: gradient (scaled to fit). Blue: chosen unit direction (scaled to fit). Circles: level curves.</div></div><section className="panel"><h2>Which way is uphill?</h2><div className="formula"><MathText tex="f(x,y)=x^2+y^2"/></div><Control label="Point x" value={x} min={-2} max={2} step={.1} onChange={setX}/><Control label="Point y" value={y} min={-2} max={2} step={.1} onChange={setY}/><Control label="Direction angle (degrees)" value={angle} min={0} max={360} onChange={setAngle}/><div className="formula"><MathText tex={`D_{\\mathbf u}f=${derivative.toFixed(3)}`}/></div><p>{Math.abs(derivative)<.03?'The first-order change in this direction is approximately zero.':derivative>0?'The function increases in this direction.':'The function decreases in this direction.'} The greatest rate of increase is {Math.hypot(2*x,2*y).toFixed(3)}.</p></section></div></TabsContent>

 <TabsContent value="region"><div className="lab-grid"><div className="plot"><svg viewBox="0 0 480 480" role="img" aria-label="Region 0 less than y less than x squared, between x equals zero and one, with a movable slice"><Grid axes={false}/><path d={areaPath} fill="#61baac38" stroke="#168e84" strokeWidth="2.5"/>{reverse?<line x1={80+320*Math.sqrt(slice)} y1={390-300*slice} x2="400" y2={390-300*slice} stroke="#d3913f" strokeWidth="5"/>:<line x1={80+320*slice} y1="390" x2={80+320*slice} y2={390-300*slice*slice} stroke="#d3913f" strokeWidth="5"/>}<path d="M60 390H425M80 412V60" stroke="#557889" strokeWidth="1.5"/><text x="68" y="408" fontSize="14" fill="#647f90">0</text><text x="396" y="411" fontSize="14" fill="#647f90">1</text><text x="55" y="96" fontSize="14" fill="#647f90">1</text><text x="426" y="397" fontSize="14" fill="#647f90">x</text><text x="65" y="56" fontSize="14" fill="#647f90">y</text><text x="290" y="160" fontSize="16" fill="#087b77">y = x²</text></svg><div className="plot-caption">The region stays the same when the order changes. The amber segment shows the inner integral.</div></div><section className="panel"><h2>Same region. New order.</h2><p>Region: 0 ≤ x ≤ 1 and 0 ≤ y ≤ x².</p><div className="row" style={{marginTop:18}}><button className={'btn '+(!reverse?'':'light')} aria-pressed={!reverse} onClick={()=>setReverse(false)}>Vertical slices</button><button className={'btn '+(reverse?'':'light')} aria-pressed={reverse} onClick={()=>setReverse(true)}>Horizontal slices</button></div><Control label={reverse?'Slice height y':'Slice position x'} value={slice} min={0} max={1} step={.01} onChange={setSlice}/><div className="formula"><MathText tex={reverse?'\\int_0^1\\int_{\\sqrt y}^1 f(x,y)\\,dx\\,dy':'\\int_0^1\\int_0^{x^2} f(x,y)\\,dy\\,dx'}/></div><p>{reverse?`At y=${slice.toFixed(2)}, x runs from ${Math.sqrt(slice).toFixed(3)} to 1.`:`At x=${slice.toFixed(2)}, y runs from 0 to ${(slice*slice).toFixed(3)}.`}</p><div className="notice info">Sketching the region first prevents reversed limits and missing parts of the domain.</div></section></div></TabsContent></Tabs></>

}

