import type {Topic} from './types';
export const topics:Topic[] = [
 {id:'series',title:'Sequences & series',short:'Sequences & series',sections:'10.1–10.8',lectures:'01–06',description:'Choose the right convergence test, then build power and Taylor series.',formula:String.raw`\sum_{n=0}^{\infty}a_n(x-c)^n`,goals:['Distinguish absolute and conditional convergence','Check endpoints of power series','Construct Maclaurin and Taylor expansions']},
 {id:'polar',title:'Polar coordinates',short:'Polar coordinates',sections:'11.3–11.4',lectures:'07–08',description:'Move between coordinate systems and understand the shape of a polar curve.',formula:String.raw`x=r\cos\theta,\quad y=r\sin\theta`,goals:['Convert Cartesian and polar equations','Sketch the included sine and cosine curves','Understand regions before setting up an integral']},
 {id:'vectors',title:'Vector functions & motion',short:'Vector functions',sections:'13.1–13.4',lectures:'09–11',description:'Connect a trajectory with its velocity, tangent, arc length, and curvature.',formula:String.raw`\kappa=\frac{|\mathbf r'\times\mathbf r''|}{|\mathbf r'|^3}`,goals:['Differentiate and integrate vector functions','Calculate arc length','Find tangent and normal vectors and curvature']},
 {id:'limits',title:'Functions, limits & continuity',short:'Limits & continuity',sections:'14.1–14.2',lectures:'12–13',description:'Read level curves and learn why checking a few paths is not enough.',formula:String.raw`\lim_{(x,y)\to(a,b)}f(x,y)`,goals:['Describe domains and level curves','Disprove a limit with two paths','Prove continuity with a bound']},
 {id:'partials',title:'Partial derivatives & chain rule',short:'Partial derivatives',sections:'14.3–14.4',lectures:'14–15',description:'Track what changes, what stays fixed, and how dependencies combine.',formula:String.raw`\frac{df}{dt}=f_x\frac{dx}{dt}+f_y\frac{dy}{dt}`,goals:['Calculate first and mixed partials','Apply the multivariable chain rule','Distinguish partial derivatives from differentiability']},
 {id:'gradient',title:'Gradients & tangent planes',short:'Gradients & tangents',sections:'14.5–14.6',lectures:'16–17',description:'Find the steepest direction and use a plane to approximate a surface.',formula:String.raw`D_{\mathbf u}f=\nabla f\cdot\mathbf u`,goals:['Normalize a direction before differentiating','Find tangent planes and normal lines','Construct a linear approximation']},
 {id:'optimization',title:'Extrema & Lagrange multipliers',short:'Optimization',sections:'14.7–14.8',lectures:'18–21',description:'Find and classify candidates, and remember the boundary.',formula:String.raw`\nabla f=\lambda\nabla g`,goals:['Classify critical points','Check boundaries for absolute extrema','Solve constrained optimization problems']},
 {id:'double',title:'Double integrals & regions',short:'Double integrals',sections:'15.1–15.4',lectures:'22–25',description:'Sketch the region, choose the order, and make the integral manageable.',formula:String.raw`\iint_R f(x,y)\,dA`,goals:['Set up iterated integrals','Reverse integration order','Transform rectangular integrals to polar form']},
 {id:'triple',title:'Triple integrals & substitutions',short:'Triple integrals',sections:'15.5, 15.7–15.8',lectures:'26–30',description:'Choose coordinates that fit the solid and include the Jacobian.',formula:String.raw`dV=\rho^2\sin\phi\,d\rho\,d\phi\,d\theta`,goals:['Describe solids in three coordinate systems','Evaluate volumes and averages','Change variables using a Jacobian']},
 {id:'line',title:'Line integrals & Green’s theorem',short:'Line integrals',sections:'16.1–16.4',lectures:'31–35',description:'Connect work, circulation, potential functions, and orientation.',formula:String.raw`\oint_C P\,dx+Q\,dy=\iint_R(Q_x-P_y)\,dA`,goals:['Distinguish scalar and vector line integrals','Check conservativity and path independence','Apply Green’s theorem with the correct orientation']},
 {id:'surface',title:'Surface integrals & theorems',short:'Surface integrals',sections:'16.5–16.8',lectures:'36–40',description:'Choose between direct integration, divergence, and Stokes’ theorem.',formula:String.raw`\iint_{\partial V}\mathbf F\cdot\mathbf n\,dS=\iiint_V\nabla\cdot\mathbf F\,dV`,goals:['Parametrize surfaces and calculate area','Calculate outward flux with divergence','Relate circulation to curl using Stokes’ theorem']},
];
